name: Unit Test

on: [push]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [
          "3.8",
          "3.9",
          "3.10",
          ]
        django-version: [
          "django>=3.2,<3.3",
          "django>=4.0,<4.1",
        ]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pip install "${{ matrix.django-version }}" --quiet
        python setup.py install
        pip install flake8
        pip install coverage

    - name: Analyze code with flake8
      continue-on-error: false
      run: |
        flake8

    - name: Django Unit Testing
      id: unittest
      continue-on-error: false
      run: |
        coverage run --source='.' quicktest.py django_classified

    - name: Generate Coverage Report
      run: |
        coverage report --show-missing
